name: Lyuping
author: Lyuping
baseurl: /dulyup.github.io
description: Tech
github: http://www.github.com/dulyup
linkedin: https://www.linkedin.com/in/lyuping-du/
email: dulyup@gmail.com
location: 47°36'22.36"N, 122°19'55.45"W
disqus: lyup

highlighter: rouge
#markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
